In [27]:
import numpy
import scipy.special

In [47]:
class neuralNetwork:
    def __init__(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        print('__init__()')
        
        # 입력, 은닉, 출력 계층 노드 개수 설정
        self.inodes = input_nodes
        self.hnodes = hidden_nodes
        self.onodes = output_nodes
        
        # 가중치 행렬 (Weight Input -> Hidden) 와 (Weight Hidden -> Out)
        self.wih = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes))
        self.who = numpy.random.normal(0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes))
        print('W I=>H', self.wih)
        print('W H=>O', self.who)
        
        # 학습률
        self.lr = learning_rate
        
        # 신경망 활성화 sigmoid 함수 정의
        self.activation_function = lambda x: scipy.special.expit(x)
        
        pass
    
    def train(self, inputs_list, targets_list):
        print('train()', inputs_list, targets_list)
        # 입력과 타겟 리스트를 2차원 행렬변환
        inputs = numpy.array(inputs_list, ndmin=2).T
        targets = numpy.array(targets_list, ndmin=2).T
        
        hidden_inputs = numpy.dot(self.wih, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        
        final_inputs = numpy.dot(self.who, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        
        # 출력 계층의 오차 (실제 값 - 계산 값)
        output_errors = targets - final_outputs
        print('output_errors', output_errors)
        # 은닉 계층의 오차 (가중치에 의해 나뉜 출력 계층의 오차들을 재조립하여 계산)
        hidden_errors = numpy.dot(self.who.T, output_errors)
        print('hidden_errors', hidden_errors)
        
        # 은닉 계층과 출력 계층 간의 가중치 업데이트
        self.who += self.lr * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))
        # 입력 계층과 은닉 계층 간의 가중치 업데이트
        self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))
        pass
    
    def query(self, inputs_list):
        print('query()', inputs_list)
        
        # input list 2차원 행렬변환
        inputs = numpy.array(inputs_list, ndmin=2).T
        
        # 은닉 계층으로 들어오는 신호를 계산
        hidden_inputs = numpy.dot(self.wih, inputs)
        # 은닉 계층에서 나가는 신호를 계산
        hidden_outputs = self.activation_function(hidden_inputs)
        # 최종 출력 계층으로 들어오는 신호를 계산
        final_inputs = numpy.dot(self.who, hidden_outputs)
        # 최종 출력 계층에서 나가는 신호를 계산
        final_outputs = self.activation_function(final_inputs)
        
        return final_outputs

In [48]:
# input, hidden, output 노드 수
input_nodes = 3
hidden_nodes = 3
output_nodes = 3

# 학습률
learning_rate = 0.3

# create instance of neural network
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

__init__()
W I=>H [[-0.16321825 -0.55136065 -0.68903476]
 [-0.159853    0.10399293 -0.40108999]
 [ 0.35671375  0.02115111  0.22590246]]
W H=>O [[ 0.20763819 -0.20558353 -1.59766442]
 [-0.068073   -0.93258723  0.08986717]
 [ 0.24839961  0.1056636   0.25284189]]


In [49]:
n.query([1.0, 0.5, -1.5])

query() [1.0, 0.5, -1.5]


array([[0.30916051],
       [0.35952437],
       [0.58756582]])